[pytest]
addopts = -v --alluredir=allure-results --clean-alluredir
testpaths = tests
python_files = test_*.py
markers =
    home_screen: tests for home page
    nav_bar: tests for nav bar
    dp_page: tests for dp page
    text_page: tests for text page
    bg_color_page: tests for background color page
    inputs_page: tests for inputs page
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)-8s | %(name)s | %(message)s
log_cli_date_format = %H:%M:%S